-- ==========================================
-- KVTC Analytics & Lead Capture Database
-- Run this in your Supabase SQL Editor
-- ==========================================

-- 1. Course Events Table (for the existing analytics module)
CREATE TABLE IF NOT EXISTS public.course_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type TEXT NOT NULL,
    course_name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Leads Table (for the WhatsApp Lead Capture)
CREATE TABLE IF NOT EXISTS public.leads (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    course TEXT,
    source TEXT DEFAULT 'exit_intent',
    status TEXT DEFAULT 'new',
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Funnel Stats Table (for the Student Lead Funnel)
CREATE TABLE IF NOT EXISTS public.funnel_stats (
    id INT PRIMARY KEY DEFAULT 1,
    page_visits INT DEFAULT 0,
    aria_chats INT DEFAULT 0,
    apply_starts INT DEFAULT 0,
    apply_completes INT DEFAULT 0,
    enrolled INT DEFAULT 0,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Initialize the funnel_stats row with zeros if it doesn't exist
INSERT INTO public.funnel_stats (id, page_visits, aria_chats, apply_starts, apply_completes, enrolled)
VALUES (1, 0, 0, 0, 0, 0)
ON CONFLICT (id) DO NOTHING;

-- Optionally, enable Row Level Security (RLS) but allow service_role to bypass
ALTER TABLE public.course_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.funnel_stats ENABLE ROW LEVEL SECURITY;

-- Note: Because we are using the SUPABASE_SERVICE_ROLE_KEY in our Next.js API, 
-- we do not need to create explicit RLS policies for our APIs to read/write.
-- The service role key automatically bypasses RLS.
