-- ==========================================
-- KVTC Analytics & Lead Capture Database
-- Run this in your Supabase SQL Editor
-- ==========================================

-- 1. Course Events Table (for the existing analytics module)
CREATE TABLE IF NOT EXISTS public.course_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type TEXT NOT NULL,
    course_name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Leads Table (for the WhatsApp Lead Capture)
CREATE TABLE IF NOT EXISTS public.leads (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    course TEXT,
    source TEXT DEFAULT 'exit_intent',
    status TEXT DEFAULT 'new',
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Funnel Stats Table (for the Student Lead Funnel)
CREATE TABLE IF NOT EXISTS public.funnel_stats (
    id INT PRIMARY KEY DEFAULT 1,
    page_visits INT DEFAULT 0,
    aria_chats INT DEFAULT 0,
    apply_starts INT DEFAULT 0,
    apply_completes INT DEFAULT 0,
    enrolled INT DEFAULT 0,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Initialize the funnel_stats row with zeros if it doesn't exist
INSERT INTO public.funnel_stats (id, page_visits, aria_chats, apply_starts, apply_completes, enrolled)
VALUES (1, 0, 0, 0, 0, 0)
ON CONFLICT (id) DO NOTHING;

-- Optionally, enable Row Level Security (RLS) but allow service_role to bypass
ALTER TABLE public.course_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.funnel_stats ENABLE ROW LEVEL SECURITY;

-- 4. ARIA Questions (anonymous product and admissions research)
CREATE TABLE IF NOT EXISTS public.aria_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question TEXT NOT NULL CHECK (char_length(question) <= 300),
    matched_course TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS aria_questions_created_at_idx
ON public.aria_questions (created_at DESC);

-- 5. ARIA Institutional Insights
-- New insights remain pending until an administrator verifies them.
CREATE TABLE IF NOT EXISTS public.aria_insights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    insight TEXT NOT NULL CHECK (char_length(insight) <= 500),
    status TEXT NOT NULL DEFAULT 'pending'
      CHECK (status IN ('pending', 'approved', 'rejected')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    reviewed_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS aria_insights_status_created_at_idx
ON public.aria_insights (status, created_at DESC);

ALTER TABLE public.aria_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.aria_insights ENABLE ROW LEVEL SECURITY;

-- 6. Distributed ARIA rate limits for serverless deployments
CREATE TABLE IF NOT EXISTS public.aria_rate_limits (
    rate_key TEXT PRIMARY KEY,
    request_count INT NOT NULL DEFAULT 0,
    window_started_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.aria_rate_limits ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.check_aria_rate_limit(
    p_key TEXT,
    p_limit INT,
    p_window_seconds INT
)
RETURNS TABLE (allowed BOOLEAN, remaining INT, retry_after INT)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    current_row public.aria_rate_limits%ROWTYPE;
    now_utc TIMESTAMP WITH TIME ZONE := timezone('utc'::text, now());
    reset_at TIMESTAMP WITH TIME ZONE;
BEGIN
    INSERT INTO public.aria_rate_limits (rate_key, request_count, window_started_at)
    VALUES (p_key, 1, now_utc)
    ON CONFLICT (rate_key) DO UPDATE
    SET request_count = CASE
          WHEN public.aria_rate_limits.window_started_at
               <= now_utc - make_interval(secs => p_window_seconds)
          THEN 1
          ELSE public.aria_rate_limits.request_count + 1
        END,
        window_started_at = CASE
          WHEN public.aria_rate_limits.window_started_at
               <= now_utc - make_interval(secs => p_window_seconds)
          THEN now_utc
          ELSE public.aria_rate_limits.window_started_at
        END
    RETURNING * INTO current_row;

    reset_at := current_row.window_started_at + make_interval(secs => p_window_seconds);
    allowed := current_row.request_count <= p_limit;
    remaining := GREATEST(0, p_limit - current_row.request_count);
    retry_after := GREATEST(0, CEIL(EXTRACT(EPOCH FROM (reset_at - now_utc)))::INT);
    RETURN NEXT;
END;
$$;

REVOKE ALL ON FUNCTION public.check_aria_rate_limit(TEXT, INT, INT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.check_aria_rate_limit(TEXT, INT, INT) TO service_role;

-- Note: Because we are using the SUPABASE_SERVICE_ROLE_KEY in our Next.js API, 
-- we do not need to create explicit RLS policies for our APIs to read/write.
-- The service role key automatically bypasses RLS.
